services:
  - type: web
    name: eld-trip-planner-api
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn config.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
